import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Button, Input } from '@components/common'
import { Header } from '@components/layout/Header/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>imaimai chat</title>
        <meta name="description" content="this chat generated by imaimai" />
        <link rel="icon" href="/frog.PNG" />
      </Head>

      <div>
        <Header />
      </div>

      <main className="align-center mx-auto flex h-90v w-4/5 flex-col items-center justify-center">
        <h1 className="my-5 text-5xl">ようこそ、いまいまいチャットへ</h1>
        <div className="my-5 flex flex-col justify-center items-center gap-5">
          <p className="text-2xl">名前を入力して始める</p>
          <div className='flex flex-row gap-5'>
            <Input placeholder="name" />
            <Button
              outlined={true}
              size={'middle'}
              onClick={() => (document.location.href = 'https://reactjs.org')}
            >
              Submit
            </Button>
          </div>
        </div>
      </main>
    </div>
  )
}
